trigger:
  branches:
    include:
      - develop
      - test
      - main

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: 'Your-Service-Connection-Name'
  appNameDev: 'func-sofascore-dev-001'
  appNameTest: 'func-sofascore-test-001'
  appNameProd: 'func-sofascore-prod-001'
  appType: 'functionAppLinux'
  pythonVersion: $(pythonVersion)

stages:

# Build and deploy for the develop branch
- stage: BuildAndDeployDev
  displayName: Build and deploy Function App to development environment
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  jobs:
  - template: ../../cicd-pipeline/az_func_build.yml
    parameters:
      environment: 'dev'
      appName: $(appNameDev)
      pythonVersion: $(pythonVersion)
  - template: ../../cicd-pipeline/az_func_deploy.yml
    parameters:
      azureSubscription: $(azureServiceConnection)
      environment: 'dev'
      appName: $(appNameDev)
      appType: $(appType)

# Build and deploy for the test branch
- stage: BuildAndDeployTest
  displayName: Build and deploy Function App to test environment
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/test')
  jobs:
  - template: ../../cicd-pipeline/az_func_build.yml
    parameters:
      environment: 'test'
      appName: $(appNameTest)
      pythonVersion: $(pythonVersion)
  - template: ../../cicd-pipeline/az_func_deploy.yml
    parameters:
      azureSubscription: $(azureServiceConnection)
      environment: 'test'
      appName: $(appNameTest)
      appType: $(appType)

# Build and deploy for the main branch
- stage: BuildAndDeployProd
  displayName: Build and Deploy to Production
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
  - template: ../../cicd-pipeline/az_func_build.yml
    parameters:
      environment: 'prod'
      appName: $(appNameProd)
      pythonVersion: $(pythonVersion) 
  - template: ../../cicd-pipeline/az_func_deploy.yml
    parameters:
      azureSubscription: $(azureServiceConnection)
      environment: 'prod'
      appName: $(appNameProd)
      appType: $(appType)


