trigger:
  branches:
    include:
      - develop
      - test
      - main

pool:
  vmImage: ubuntu-latest

variables:
  devAppName: 'func-sofascore-dev-001'
  testAppName: 'func-sofascore-test-001'
  prodAppName: 'func-sofascore-prod-001'
  azureServiceConnection: 'Your-Service-Connection-Name'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - template: cicd-pipeline/az_func_build.yml

- stage: DeployDev
  displayName: Deploy to development
  dependsOn: Build
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  jobs:
  - job: DeployDev
    displayName: Deploy to development Function App
    steps:
    - template: cicd-pipeline/az_func_deploy.yml
      parameters:
        azureSubscription: $(azureServiceConnection)
        appName: $(devAppName)

- stage: DeployTest
  displayName: Deploy to test
  dependsOn: Build
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/test')
  jobs:
  - job: DeployTest
    displayName: Deploy to test Function App
    steps:
    - template: cicd-pipeline/az_func_deploy.yml
      parameters:
        azureSubscription: $(azureServiceConnection)
        appName: $(testAppName)

- stage: DeployProd
  displayName: Deploy to production
  dependsOn: Build
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
  - job: DeployProd
    displayName: Deploy to production Function App
    steps:
    - template: cicd-pipeline/az_func_deploy.yml
      parameters:
        azureSubscription: $(azureServiceConnection)
        appName: $(prodAppName)


