# Azure Functions Deploy v2
# Update a function app with .NET, Python, JavaScript, PowerShell, Java based web applications.

parameters:
- name: azureSubscription
  type: string
- name: environment
  type: string
- name: appName
  type: string
- name: appType
  type: string
  default: 'functionAppLinux'

jobs:
- job: functionApp_${{ parameters.appName }}_${{ parameters.environment }}_build
  displayName: Deploy Function App
  steps:
  - task: AzureFunctionApp@2
    displayName: Deploy Azure Function App
    inputs:
      connectedServiceNameARM: ${{ parameters.azureSubscription }}
      appType: ${{ parameters.appType }}
      appName: ${{ parameters.appName }}
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'
      deploymentMethod: 'auto'

